load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "lib_bytemachine",
    srcs = ["lib_bytemachine.py"],
    deps = [
        "//src/orca:actuator",
        "//src/orca:constants"
    ],
    visibility = ["//visibility:public"],
)
